### ISSUE TITLE
SDK for OpenStorage

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#407]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE

**Description**:
The SDK for OpenStorage will provide developers with ability to programatically control OpenStorage based storage systems like Portworx. Developers will be provided with documentation, an API, clients for multiple languages, and an mock storage application to test and develop their code.

**Architecture**:
The SDK will run a gRPC server which will communicate with the OpenStorage interfaces, exporting only the objects and API functions to be consumed by external developers. See diagram below:

```
+------------+
|            |        +------------+
|   Current  |        |            |
|   REST     |        |  gRPC SDK  |
|            |        |            |
+------------+--------+------------+
|                                  |
|    OpenStorage Interfaces        |
|                                  |
+----------------------------------+
```

**Tasks**:
- [x] Share gRPC code with current CSI server to minimize duplication
- [x] Update `api.proto` with the RPC and Messages needed for the SDK
- [x] Update https://libopenstorage.github.io with documentation based on `api.proto`.
- [x] Create a server which serves gRPC for the SDK in `api/server/sdk`
- [x] Create an implementation for Cluster calls (including unit tests)
- [x] Create an implementation for Volume calls (including unit tests)
- [x] Update `Makefile` to create clients in Python, Ruby, Golang and place them in `api/client/sdk`
- [x] Create a fake in-memory driver implementation which can be used to create a simple application for developers to communicate with while developing and testing their code.

**Cloud APIs**:
- [x] Cloud Credentials APIs
- [x] Scheduling Policy

**Volume APIs**:
- [ ] Stat?
- [x] Cloud Backup
- [ ] Cloud Backup Scheduling
- [x] Object Storage

**Fake Driver**
- [x] Support Credentials
- [x] Support CloudBackup

Once done, we need a:
- [ ] Finalize documentation
- [ ] Full Review of the API

**Comment by lpabon** [comment]
features tracked by project.
